import { ArrowUpRight, Megaphone, MoreHorizontal, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils";

const campaigns = [
  { name: "Summer Retargeting", channel: "Meta Ads", status: "Active", budget: 12000, spent: 8420, revenue: 29840 },
  { name: "Brand Search", channel: "Google Ads", status: "Active", budget: 8500, spent: 5360, revenue: 18200 },
  { name: "New Arrivals Launch", channel: "Email", status: "Draft", budget: 2400, spent: 0, revenue: 0 },
];

export default function CampaignsPage() {
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.08em] text-text-muted">Growth</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Campaigns</h1><p className="mt-2 text-sm text-text-muted">Plan spend and compare channel performance.</p></div><Button><Plus className="size-4" />New campaign</Button></div><section className="grid gap-4 sm:grid-cols-3"><Card className="p-card"><p className="text-sm text-text-muted">Active campaigns</p><p className="mt-3 text-2xl font-semibold tabular-nums">2</p></Card><Card className="p-card"><p className="text-sm text-text-muted">Total ad spend</p><p className="mt-3 text-2xl font-semibold tabular-nums">$13,780</p></Card><Card className="p-card"><p className="text-sm text-text-muted">Blended ROAS</p><p className="mt-3 text-2xl font-semibold tabular-nums">3.49×</p></Card></section><div className="grid gap-4">{campaigns.map((campaign) => { const progress = campaign.budget ? campaign.spent / campaign.budget * 100 : 0; return <Card key={campaign.name} className="p-card transition-[box-shadow,translate] duration-200 hover:-translate-y-0.5 hover:shadow-[var(--shadow-border-hover)]"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="flex size-11 items-center justify-center rounded-[calc(var(--input-radius)+0.25rem)] bg-surface-soft"><Megaphone className="size-5 text-text-muted" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{campaign.name}</h2><Badge variant={campaign.status === "Active" ? "success" : "neutral"}>{campaign.status}</Badge></div><p className="mt-1 text-xs text-text-muted">{campaign.channel}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-surface-soft"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} /></div></div><div className="grid grid-cols-3 gap-5 text-right"><div><p className="text-xs text-text-subtle">Budget</p><p className="mt-1 text-sm font-semibold tabular-nums">{formatCurrency(campaign.budget)}</p></div><div><p className="text-xs text-text-subtle">Spent</p><p className="mt-1 text-sm font-semibold tabular-nums">{formatCurrency(campaign.spent)}</p></div><div><p className="text-xs text-text-subtle">Revenue</p><p className="mt-1 text-sm font-semibold tabular-nums">{formatCurrency(campaign.revenue)}</p></div></div><Button variant="ghost" size="icon" aria-label={`Options for ${campaign.name}`}><MoreHorizontal className="size-4" /></Button></div></Card>; })}</div><Button variant="secondary">Open campaign report<ArrowUpRight className="size-4" /></Button></div>;
}
