import { Check, CreditCard, ExternalLink, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function BillingPage() {
  const features = ["Unlimited data sources", "Advanced campaign analytics", "10 team members", "Priority support"];
  return <div className="space-y-6"><div><p className="text-xs font-medium uppercase tracking-[0.08em] text-text-muted">Management</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Billing & Subscription</h1><p className="mt-2 text-sm text-text-muted">Manage your plan, usage, and payment details.</p></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_22rem]"><Card className="overflow-hidden"><div className="flex flex-col gap-6 bg-zinc-950 p-card text-white sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Sparkles className="size-4" /><p className="text-sm font-medium">Vektorix Pro</p><Badge className="bg-white/10 text-white">Active</Badge></div><p className="mt-5 text-3xl font-semibold tracking-[-0.04em] tabular-nums">$79<span className="text-sm font-normal text-zinc-400"> / month</span></p><p className="mt-2 text-sm text-zinc-400">Renews on August 22, 2026</p></div><Button className="bg-white text-zinc-950 hover:bg-zinc-100">Manage plan<ExternalLink className="size-4" /></Button></div><div className="grid gap-3 p-card sm:grid-cols-2">{features.map((feature) => <p key={feature} className="flex items-center gap-2 text-sm text-text-muted"><span className="flex size-5 items-center justify-center rounded-full bg-accent-green-soft text-emerald-700"><Check className="size-3" /></span>{feature}</p>)}</div></Card><Card className="p-card"><div className="flex size-10 items-center justify-center rounded-[calc(var(--input-radius)+0.25rem)] bg-surface-soft"><CreditCard className="size-4" /></div><h2 className="mt-5 font-semibold">Payment method</h2><p className="mt-2 text-sm text-text-muted">Visa ending in 4242</p><p className="mt-1 text-xs text-text-subtle">Expires 09/28</p><Button variant="secondary" className="mt-6 w-full">Update card</Button></Card></div></div>;
}
